name: verum_agro_trading
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  get_it: ^7.6.7
  equatable: ^2.0.5
  logger: ^2.0.2+1
  go_router: ^13.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  mockito: ^5.4.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/images/verum_launcher_4x.png"
  image_path_ios: "assets/images/verum_launcher_4-1.png"
  remove_alpha_ios: true
  adaptive_icon_background: #203745
  adaptive_icon_foreground: "assets/images/verum_launcher_4-1.png"

flutter_native_splash:
  image_android: "assets/images/verum_splash_logo_1x.png"
  image_ios: "assets/images/verum_splash_logo.png"
  color: "#203745"
  # branding: "assets/images/verum_launcher_4x.png"
  android_12:
    image: "assets/images/verum_splash_logo_1x.png"
    color: "#203745"
    # branding: "assets/images/verum_launcher_4x.png"
  web: false



flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
