// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD2oPKkN8yoSaEZdIAS5lSegxjgcI_YvAE',
    appId: '1:635023075181:web:7f69f7379122815a4c9c64',
    messagingSenderId: '635023075181',
    projectId: 'verum-agro',
    authDomain: 'verum-agro.firebaseapp.com',
    storageBucket: 'verum-agro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe8mWPGREHO3QVE1Vt0HYSui2UP-seFWI',
    appId: '1:635023075181:android:71c7159b2357da624c9c64',
    messagingSenderId: '635023075181',
    projectId: 'verum-agro',
    storageBucket: 'verum-agro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO9tKp3n0BVh2m6a9pnjfb3g8aKoHVVrc',
    appId: '1:635023075181:ios:974f69c3ecb627de4c9c64',
    messagingSenderId: '635023075181',
    projectId: 'verum-agro',
    storageBucket: 'verum-agro.appspot.com',
    iosBundleId: 'in.manavgarg.verumAgroTrading',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO9tKp3n0BVh2m6a9pnjfb3g8aKoHVVrc',
    appId: '1:635023075181:ios:48a170a1492ac70d4c9c64',
    messagingSenderId: '635023075181',
    projectId: 'verum-agro',
    storageBucket: 'verum-agro.appspot.com',
    iosBundleId: 'in.manavgarg.verumAgroTrading.RunnerTests',
  );
}
